services:
  mihomo_42257_42288:
    container_name: mihomo_42257_42288
    restart: always
    network_mode: host
    volumes:
    - type: bind
      bind:
        propagation: rprivate
      source: D:\Codes\pythonCodes\aggregator\submanager\mihomo\configs\mihomo_42257_42288.yml
      target: /etc/mihomo/config.yaml
    image: metacubex/mihomo
    command: -f /etc/mihomo/config.yaml
  mihomo_42288_42290:
    container_name: mihomo_42288_42290
    restart: always
    network_mode: host
    volumes:
    - type: bind
      bind:
        propagation: rprivate
      source: D:\Codes\pythonCodes\aggregator\submanager\mihomo\configs\mihomo_42288_42290.yml
      target: /etc/mihomo/config.yaml
    image: metacubex/mihomo
    command: -f /etc/mihomo/config.yaml
  mihomo_42290_42335:
    container_name: mihomo_42290_42335
    restart: always
    network_mode: host
    volumes:
    - type: bind
      bind:
        propagation: rprivate
      source: D:\Codes\pythonCodes\aggregator\submanager\mihomo\configs\mihomo_42290_42335.yml
      target: /etc/mihomo/config.yaml
    image: metacubex/mihomo
    command: -f /etc/mihomo/config.yaml
  mihomo_42335_42390:
    container_name: mihomo_42335_42390
    restart: always
    network_mode: host
    volumes:
    - type: bind
      bind:
        propagation: rprivate
      source: D:\Codes\pythonCodes\aggregator\submanager\mihomo\configs\mihomo_42335_42390.yml
      target: /etc/mihomo/config.yaml
    image: metacubex/mihomo
    command: -f /etc/mihomo/config.yaml
